version: "3.5"
services:
  backend:
    build: 
      context: ./src/backend
      dockerfile: Dockerfile
      target: development
    image: backend
    container_name: backend
    volumes:
      - ./src/backend:/transcendence/backend
      - /transcendence/backend/node_modules
    command: npm run start:debug
    networks:
      - transcendence_network
    depends_on:
      - postgres
    ports:
      - 3000:3000
      - 5555:5555 # prisma studio
    env_file:
      - ./src/postgres/dev.env
    restart: on-failure

  frontend:
    build: 
      context: ./src/frontend
      dockerfile: Dockerfile
      target: development
    image: frontend
    container_name: frontend
    volumes:
      - ./src/frontend:/transcendence/frontend
      - /transcendence/frontend/node_modules
    command: npm run start
    ports:
      - 4200:4200
    networks:
      - transcendence_network
    restart: on-failure
  
  postgres:
    build: 
      context: ./src/postgres/docker
      dockerfile: Dockerfile
    image: postgres
    container_name: postgres
    networks:
      - transcendence_network
    env_file:
      - ./src/postgres/dev.env
    restart: on-failure
    ports:
      - 5432:5432
    # TODO: add a volume

networks:
  transcendence_network:
      driver: bridge
