version: "3.5"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - transcendence_files:/var/www
    networks:
      - transcendence_network
    restart: on-failure

  backend:
    build: 
      context: ../
      dockerfile: docker/nestjs/Dockerfile
    image: nestjs
    container_name: nestjs
    volumes:
      - transcendence_files:/var/www
    networks:
      - transcendence_network
    depends_on:
      - nginx
      - postgres
    restart: on-failure

  frontend:
    build: 
      context: ../
      dockerfile: docker/angular/Dockerfile
    image: angular
    container_name: angular
    volumes:
      - transcendence_files:/var/www
    networks:
      - transcendence_network
    depends_on:
      - nginx
    restart: on-failure
  
  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    image: postgres
    container_name: postgres
    volumes:
      - transcendence_db:/var/lib/
    networks:
      - transcendence_network
    restart: on-failure
    
volumes:
  transcendence_files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Volumes/data/site

  transcendence_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Volumes/data/postgres

networks:
  transcendence_network:
      driver: bridge
